### ISSUE TITLE
Final results

### ISSUE THREAD

**Issue by mpariente** [JusperLee/Deep-Clustering-for-Speech-Separation#1]
Hey Jusper Lee, 

Thanks again for this implementation. 
Which are the final results that you obtain? 
Would you have a logfile or learning curve to share? 

Thanks!

**Comment by JusperLee** [comment]
![image](https://user-images.githubusercontent.com/33806018/81468218-c7f3d800-9210-11ea-8d3b-17cf31a94ab4.png)

Final results: 9.5

**Comment by mpariente** [comment]
Thank you very much !
