### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by hsecreto** [JusperLee/Deep-Clustering-for-Speech-Separation#2]
Hi, @JusperLee , thanks for sharing the implementations of speech separation models. Could you please update the link with the pre-trained models? It seems it's not working.

**Comment by JusperLee** [comment]
I have updated Readme.

**Comment by ghost** [comment]
I can not find link in readme. Can you give URL?

**Comment by JusperLee** [comment]
https://github.com/JusperLee/Deep-Clustering-for-Speech-Separation/tree/master/checkpoint
