### ISSUE TITLE
Inference error

### ISSUE THREAD

**Issue by srdfjy** [JusperLee/Deep-Clustering-for-Speech-Separation#9]
python test.py -scp test/test.scp -opt config/test.yml -save_file test/result/

--------------------------------------------------------------------------------

Traceback (most recent call last):
  File "test.py", line 111, in <module>
    separation = Separation(dpcl, args.scp, opt, args.save_file)
  File "test.py", line 35, in __init__
    self.dpcl.load_state_dict(ckp['model_state_dict'])
  File "/data/home/test/Deep-Clustering-for-Speech-Separation/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DPCL:
        Unexpected key(s) in state_dict: "blstm.weight_ih_l2", "blstm.weight_hh_l2", "blstm.bias_ih_l2", "blstm.bias_hh_l2", "blstm.weight_ih_l2_reverse", "blstm.weight_hh_l2_reverse", "blstm.bias_ih_l2_reverse", "blstm.bias_hh_l2_reverse", "blstm.weight_ih_l3", "blstm.weight_hh_l3", "blstm.bias_ih_l3", "blstm.bias_hh_l3", "blstm.weight_ih_l3_reverse", "blstm.weight_hh_l3_reverse", "blstm.bias_ih_l3_reverse", "blstm.bias_hh_l3_reverse". 
        size mismatch for blstm.weight_ih_l0: copying a param with shape torch.Size([1200, 129]) from checkpoint, the shape in current model is torch.Size([2400, 129]).
        size mismatch for blstm.weight_hh_l0: copying a param with shape torch.Size([1200, 300]) from checkpoint, the shape in current model is torch.Size([2400, 600]).
        size mismatch for blstm.bias_ih_l0: copying a param with shape torch.Size([1200]) from checkpoint, the shape in current model is torch.Size([2400]).
        size mismatch for blstm.bias_hh_l0: copying a param with shape torch.Size([1200]) from checkpoint, the shape in current model is torch.Size([2400]).
        size mismatch for blstm.weight_ih_l0_reverse: copying a param with shape torch.Size([1200, 129]) from checkpoint, the shape in current model is torch.Size([2400, 129]).
        size mismatch for blstm.weight_hh_l0_reverse: copying a param with shape torch.Size([1200, 300]) from checkpoint, the shape in current model is torch.Size([2400, 600]).
        size mismatch for blstm.bias_ih_l0_reverse: copying a param with shape torch.Size([1200]) from checkpoint, the shape in current model is torch.Size([2400]).
        size mismatch for blstm.bias_hh_l0_reverse: copying a param with shape torch.Size([1200]) from checkpoint, the shape in current model is torch.Size([2400]).
        size mismatch for blstm.weight_ih_l1: copying a param with shape torch.Size([1200, 600]) from checkpoint, the shape in current model is torch.Size([2400, 1200]).
        size mismatch for blstm.weight_hh_l1: copying a param with shape torch.Size([1200, 300]) from checkpoint, the shape in current model is torch.Size([2400, 600]).
        size mismatch for blstm.bias_ih_l1: copying a param with shape torch.Size([1200]) from checkpoint, the shape in current model is torch.Size([2400]).
        size mismatch for blstm.bias_hh_l1: copying a param with shape torch.Size([1200]) from checkpoint, the shape in current model is torch.Size([2400]).
        size mismatch for blstm.weight_ih_l1_reverse: copying a param with shape torch.Size([1200, 600]) from checkpoint, the shape in current model is torch.Size([2400, 1200]).
        size mismatch for blstm.weight_hh_l1_reverse: copying a param with shape torch.Size([1200, 300]) from checkpoint, the shape in current model is torch.Size([2400, 600]).
        size mismatch for blstm.bias_ih_l1_reverse: copying a param with shape torch.Size([1200]) from checkpoint, the shape in current model is torch.Size([2400]).
        size mismatch for blstm.bias_hh_l1_reverse: copying a param with shape torch.Size([1200]) from checkpoint, the shape in current model is torch.Size([2400]).
        size mismatch for linear.weight: copying a param with shape torch.Size([5160, 600]) from checkpoint, the shape in current model is torch.Size([5160, 1200]).

**Comment by amazing00adam** [comment]
hi
 bro
I have the same problem

**Comment by amazing00adam** [comment]
have you solved it

**Comment by JusperLee** [comment]
This should be a problem with the length of the model input, and the length can be standardized.

**Comment by amazing00adam** [comment]
那请问应该如何修改呢？是代码中某一块有对应的参数吗？谢谢

**Comment by JusperLee** [comment]
python test.py -scp test/test.scp -opt config/train.yml -save_file test/result/
